---
apiVersion: v1
kind: Pod
metadata:
  name: eb-ms-pod
  labels:
    env: UAT-env
    app: eb-ms-app
  namespace: uat
spec:
  containers:
    - name: eb-ms-instance
      image: nginx
      ports:
        - name: http
          containerPort: 80
    - name: eb-tomcat-instance
      image: tomcat
      ports:
        - name: java
          containerPort: 8080
